### ISSUE TITLE
Provide an napi method for oxc_query

### ISSUE THREAD

**Issue by pastelsky** [web-infra-dev/oxc#1140]
Would it be possible to publish APIs from `oxc_query` as a part of `@oxidation-compiler/napi` (or another package)? 

That'd make it a parser-traverser pair that can open up a lot of use cases for the fast oxidation compiler.

**Comment by Boshen** [comment]
Interesting. Are you able to setup an example repo leveraging `oxc_query` by importing the crate from a github url? I want see if it is worth the effort to maintain its release.

**Comment by pastelsky** [comment]
Hi Boshen, I'm not really sure what you want to see from the example repo — but maybe I didn't state my use case well.

A lot of tools today use the `@babel/parser` / `@babel/traverse` libraries to derive insights from ASTs. The OXC playground has a excellent example of the same using the trustfall query system — but it appears that the query engine is built in wasm only for for the purpose of the demo site.

Having this available as a JS package would allow for use cases served by libraries like `esquery`, and perhaps in the future, even simple general purpose code transformers.

**Comment by pastelsky** [comment]
Also, I can't really write much rust yet — but happy to try and contribute if there's a previous example of how this was done.

**Comment by Boshen** [comment]
I see. Due to the lack of resources I'm really conservative around maintaining more releases, so unless there is a specific use case that comes up from the community.

btw the `oxc_query` crate is still work in progress and the maintainer is off to school, which means there is actually no one maintaining it at the moment.

**Comment by Boshen** [comment]
> A lot of tools today use the @babel/parser / @babel/traverse libraries to derive insights from ASTs.

It feels like there is a confusion around how the linter works.

On the Rust side we are using the visitor pattern https://github.com/web-infra-dev/oxc/blob/main/crates/oxc_ast/src/visit.rs

The `oxc_query` crate is meant to be used with the linter plugin, where we use a DSL to query the AST, e.g. https://github.com/web-infra-dev/oxc/blob/main/crates/oxc_linter_plugin/examples/queries/next/google-font-display/display-has-bad-value.yml

**Comment by pastelsky** [comment]
Yeah I understand the difference between oxc_ast and oxc_query.

I found the use of trustfall for querying ASTs quite novel – so having that
exposed in the JS side would be useful.

If that’s tougher to maintain, a simple visitor for oxc’s AST would do as
well – assuming you’re pre-semver and can make breaking changes at will.

I’m currently using ‘ast-traverse’ on top of oxc’s parser, but it’s quite
low level and traversing of large ASTs isn’t as fast as it could be if the
parser-query system could communicate in rust land.

A parse-query-print system could make for really fast code transformers.

**Comment by Boshen** [comment]
Ok, so the conclusion here is that `oxc_query` can be published if there is a motivation such as a concrete usage example.

I'll close this as not planned for now, feel free to reach out again if something interesting comes up.
