### ISSUE TITLE
eslint-plugin-jest(expect-expect): Test has no assertions doesn't detect `await expect`

### ISSUE THREAD

**Issue by AdriVanHoudt** [web-infra-dev/oxc#1199]
Example/repro: https://web-infra-dev.github.io/oxc/playground/?code=3YCAAIBbgICAgICAgICymcpMQXaQyDS16nxFlbtxtP%2BMSKVFtAtOuK0KxOd5yZZIDZ6aPffpelHMF6bQ%2B7gY252lRXrzFB%2B%2BRGTXX5q1pS348zzLEWhdwzIMz65QtMB1YvkivIIUlO0RZpATrjDPvCu9aonwQyafh2Y6L0CVdoNxPNccyq2jEG%2Bn2OWPKuKv3dTpTQCiLjlPqHRYZCP2nDJZf95vAIA%3D

Removing the `await` makes the warning go away.

**Comment by mysteryven** [comment]
Thanks for using the Jest rule plugin, it will be fixed soon. If you have any rules want to have, just let us know!

**Comment by AdriVanHoudt** [comment]
That was fast, thanks! 🚀

**Comment by AdriVanHoudt** [comment]
As to rules wanted: https://typescript-eslint.io/rules/no-floating-promises/ and https://typescript-eslint.io/rules/no-misused-promises mainly, not sure if this is planned already

**Comment by Boshen** [comment]
> As to rules wanted: https://typescript-eslint.io/rules/no-floating-promises/ and https://typescript-eslint.io/rules/no-misused-promises mainly, not sure if this is planned already

We are handcuffed with type information for these two rules :-(

**Comment by AdriVanHoudt** [comment]
> > As to rules wanted: [typescript-eslint.io/rules/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises/) and [typescript-eslint.io/rules/no-misused-promises](https://typescript-eslint.io/rules/no-misused-promises) mainly, not sure if this is planned already
> 
> We are handcuffed with type information for these two rules :-(

As in, these will never be possible in oxc?
