### ISSUE TITLE
fuzz-js

### ISSUE THREAD

**Issue by bakkot** [web-infra-dev/oxc#255]
`async` is, alas, a legal identifier in JS, which means all of the following are valid programs:

```js
async(...null)
```
```
null?async():null
```
```js
switch(null){case async():}
```

But they're all rejected by the parser (or at least the version of it on Cargo).

I found these with [a fuzzer](https://github.com/bakkot/fuzz-js); if you'd like me not to file bugs found by a fuzzer, let me know.

**Comment by Boshen** [comment]
Thank you for fuzzing oxc! I did a basic triage and found the parser cannot distinguish whether these are async functions or not. I'll try and get a fix soon.

**Comment by Boshen** [comment]
@bakkot I published the latest fixes

```
oxc_ast = "0.0.4"
oxc_parser = "0.0.4"
```

**Comment by Boshen** [comment]
I couldn't try `fuzz-js` due to unpublished version of `shift-shrink@2.0.0`

**Comment by bakkot** [comment]
That does seem to have fixed the `async` issues! Now the fuzzer gets further and has encountered another class of failures:

```js
for(var[l=null in null]in null);
```
```js
for(new null(null in null);;);
```
```js
for(`${null in null}`;;);
```
```js
for(new null(null in null)._ in null);
```

> I couldn't try `fuzz-js` due to unpublished version of `shift-shrink@2.0.0`

Lol, whoops, I'll get that published later today.

**Comment by Boshen** [comment]
@bakkot I published the latest fixes

```
oxc_ast = "0.0.5"
oxc_parser = "0.0.5"
```

Still waiting for `shift-shrink@2.0.0` 😁

**Comment by bakkot** [comment]
Sorry for the delay; there's some stuff blocking. I'll ping you when I get it actually released.

**Comment by bakkot** [comment]
Well, that took an embarrassingly long time, but shift-shrink 2.0.0 is now published.

**Comment by Boshen** [comment]
@bakkot Thank you, it's running locally.

**Comment by Boshen** [comment]
I got it working https://github.com/Boshen/oxc-fuzz-parser
