### ISSUE TITLE
Can't recover after input `～` in the playground

### ISSUE THREAD

**Issue by mysteryven** [web-infra-dev/oxc#426]
[Playground](https://boshen.github.io/oxc/playground/?code=Xv8%3D)

After input `～`, the playground breaks down.

**Comment by Boshen** [comment]
This is due to unicode 8 vs 16 span positions, I totally forgot about it 😢

**Comment by addisoncrump** [comment]
@jasikpark maybe an answer to your mysterious bug in the other JS target you were working on.
