### ISSUE TITLE
 Round-trip fuzzers

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/oxc#427]
See
* https://github.com/rome/tools/pull/4559

**Comment by addisoncrump** [comment]
Feel free to assign me on this one :slightly_smiling_face: Amusingly, I actually also helped write the ezno fuzzers as well... :wink: https://github.com/jasikpark/ezno/pull/1

**Comment by Boshen** [comment]
The Oxc parser had been sniped by two other fuzzers, let me welcome you for the third one!

* https://github.com/Boshen/oxc/tree/main/crates/oxc_parser/fuzz
* https://github.com/Boshen/oxc/issues/255
* https://github.com/Boshen/oxc/issues/232

**Comment by addisoncrump** [comment]
cc @jasikpark, you mentioned wanting to do this in Signal a few days ago.

**Comment by Boshen** [comment]
Close as not planned for now, feel free to reopen if you wish to work on this again.
