### ISSUE TITLE
eslint-plugin-import/no-self-import rule

### ISSUE THREAD

**Issue by anonrig** [web-infra-dev/oxc#440]
I've started working on this. Here are my concerns/questions:

- How can I get the current file name from the context?
- How can I pass the current file name from the context?
- How does `oxc` handle extensions? Do I need to care about it in the implementation?

**Comment by Boshen** [comment]
For getting all the module requests: https://docs.rs/oxc_semantic/0.0.6/oxc_semantic/struct.Semantic.html#method.module_record

For setting and getting the current file path, we should add one to `ModuleRecord`.

For starters, let's just check for a dot `.` to get the infra going, we'll eventually need a module path resolver for getting the resolved path for each module request.

In the end, this rule will just check `ModuleRecord`, we don't need to test the AST at all.

**Comment by Boshen** [comment]
This is done. After 3 months of implementing every required dependency for this feature. I'm genuinely happy.
