### ISSUE TITLE
refactor(ast): add SymbolId and ReferenceId

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/oxc#510]
This will make the linter easier to write when you need to get the binding for a given identifier reference.

This is already done for the HIR, I just need to combine the code for the AST.

- [ ] https://github.com/Boshen/oxc/pull/508#discussion_r1250080292
- [ ] Need to fix: https://github.com/Boshen/oxc/pull/508#issuecomment-1618850742
- [ ] https://github.com/Boshen/oxc/issues/510

**Comment by mysteryven** [comment]
I may need this too.

**Comment by hyf0** [comment]
I have met similar situation. I have to traverse the AST. With this requirement, to get the `SymbolId` of some `identifier`s, I need to get the `atom` of the `Identifier`, perform a query on `ScopeTree` to get `SymbolId` and thanks for I only care about the ids of root scope, so I don't need to search which scope the `atom` in.

**Comment by Boshen** [comment]
@mysteryven You may start fixing all the issues we have accumulated 😅
