### ISSUE TITLE
CI: Ecosystem CI

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/oxc#511]
For preventing breakage in real codebases. e.g. https://github.com/Boshen/oxc/pull/508#issuecomment-1618850742

We should run oxlint on a number of repos, e.g. vscode.

See also ecosystem CI from Ruff: https://github.com/astral-sh/ruff/blob/6acc316d19ad4a9d24a1ed46b6020b84c5a3c28a/scripts/Dockerfile.ecosystem

**Comment by Leonard53** [comment]
Hi, if you don't mind I could attempt this issue. First time contributing to open source project so I hope I could help

**Comment by Boshen** [comment]
> Hi, if you don't mind I could attempt this issue. First time contributing to open source project so I hope I could help

I have assigned this issue to you, have fun!
