### ISSUE TITLE
feat(linter): eslint/no-extra-boolean-cast

### ISSUE THREAD

**Issue by DonIsaac** [web-infra-dev/oxc#596]
Implement ESLint's [`no-extra-boolean-cast`](https://eslint.org/docs/latest/rules/no-extra-boolean-cast) rule.

Start by running `just new-rule no extra-boolean-cast`, then use the [rule source](https://github.com/eslint/eslint/blob/main/lib/rules/no-extra-boolean-cast.js) and [test cases](https://github.com/eslint/eslint/blob/main/tests/lib/rules/no-extra-boolean-cast.js) as guides.

**Comment by metreniuk** [comment]
Hey, I would like to work on this issue. It seems like the easiest way to go is mirroring the eslint test cases. Do you have any additional recommandations except the ones from the repo docs?

**Comment by DonIsaac** [comment]
Absolutely, go for it! Running the setup command mentioned above will automatically create test cases for you, copying the ones from ESLint. My advice is to use other rules and ESLint's implementation as references. Feel free to drop a message in our Discord if you need advice.
