### ISSUE TITLE
feat(linter): eslint/no-redeclare

### ISSUE THREAD

**Issue by DonIsaac** [web-infra-dev/oxc#615]
Implement ESLint's [`no-redeclare`](https://eslint.org/docs/latest/rules/no-redeclare#rule-details) rule.

To get started, run
```sh
just new-rule no-redeclare
```

**Comment by DonIsaac** [comment]
@Boshen I think we don't need this rule as redeclaration checks are done during semantic analysis?

**Comment by Boshen** [comment]
> @Boshen I think we don't need this rule as redeclaration checks are done during semantic analysis?

The rule is for `var` declarations, which isn't part of the ecma spec. Can you give me a case where you found a mismatch?
