### ISSUE TITLE
Code path analysis

### ISSUE THREAD

**Issue by suica** [web-infra-dev/oxc#651]
Eslint implements [code path analysis](https://github.com/eslint/eslint/pull/3559), which allows eslint to use control-flow information to implement following rules:
- [ ] https://github.com/web-infra-dev/oxc/issues/621
- [ ] https://github.com/web-infra-dev/oxc/issues/597
- [x] constructor-super (current OXC does some workarounds to implement this, but dropped some test cases from eslint (for all test cases, see [1]))
- [ ] https://github.com/web-infra-dev/oxc/issues/618
- [ ] ~consistent-return (it is not in the eslint recommended list and could be ignored for now)~

Oxc also needs such mechanism to implement those rules precisely.

Discussions can be found at https://github.com/web-infra-dev/oxc/discussions/222

[1]: https://github.com/eslint/eslint/blob/1a2f966fabe35103141d2f936180d2f1a72154db/tests/lib/rules/constructor-super.js#L4

**Comment by u9g** [comment]
see also: https://github.com/web-infra-dev/oxc/discussions/222

**Comment by suica** [comment]
Close as dup. Discussions can be found at https://github.com/web-infra-dev/oxc/discussions/222
