### ISSUE TITLE
bug(linter): incorrect no-loss-of-precision

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/oxc#656]
From the vscode codebase

![image](https://github.com/web-infra-dev/oxc/assets/1430279/62cb28f0-a24a-4cac-bde6-cb4703b631ec)

cc @Devin-Yeung

**Comment by Devin-Yeung** [comment]
Already reproduced the bug 😢 , my previous implementation highly follow the eslint's implementation, but it relied on some behavior of the `toPrecision` function, and it may take me some time to figure out a better solution in rust.
