### ISSUE TITLE
publish vscode extension

### ISSUE THREAD

**Issue by cijiugechu** [web-infra-dev/oxc#688]
I've recently been building a vscode extension for oxc, @Boshen , if you don't mind, could I submit a PR to commit this part of the code to the repository?

#### 1. Displaying diagnostics, help messages and the range of labels

![1](https://github.com/web-infra-dev/oxc/assets/32487868/9680439c-8225-4a00-8ba3-f4ce9be124b7)
#### 2. Providing quick fix

![2](https://github.com/web-infra-dev/oxc/assets/32487868/82950a54-d410-4da1-9392-e13639e1e16a)
#### 3. Providing commands such as `restart server`

![3](https://github.com/web-infra-dev/oxc/assets/32487868/157b8321-692d-4c45-a692-6dab158d5349)

**Comment by Boshen** [comment]
Oh wow, let's do this!

**Comment by Boshen** [comment]
Code is done, I need to find the time to publish this thing :-/

**Comment by kaleidawave** [comment]
Does this include the type checking errors/diagnostics from `oxc_type_synthesis`? Last time I remember that the diagnostics were separated. We should figure out how to turn `EznoDiagnostic` into ones produced by the linter so that the CLI reporting and everything is the same.

**Comment by roonie007** [comment]
@Boshen any updates on the publishing date ?

**Comment by Boshen** [comment]
> @Boshen any updates on the publishing date ?

No ETA yet.

**Comment by Vincent-liuwingsang** [comment]
need any help with this? would love to try this in vscode

**Comment by camc314** [comment]
> need any help with this? would love to try this in vscode

you can test it out with:

cd editors/vscode
pnpm run vscode (builds server + client +packages it)

then head to vscode, command pallet "Extensions: Install from VSIX..."

find the file we just built (should be: `./oxc-vscode-0.0.1.vsix ` or similar and install

**Comment by Boshen** [comment]
Finally!

<img width="1295" alt="image" src="https://github.com/web-infra-dev/oxc/assets/1430279/d75a1337-327d-47b1-8daf-a8dfef3f225c">
