### ISSUE TITLE
`Program` borrows `source_text` unnecessarily

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/oxc#709]
I'm not sure the use case. But more accurate lifetimes after this PR allow us to have the AST while being droped the `source_text`.

![image](https://github.com/web-infra-dev/oxc/assets/49502170/b8d4fb96-1a0d-467a-a7f6-013446bf3589)

_Originally posted by @hyf0 in https://github.com/web-infra-dev/oxc/issues/701#issuecomment-1670701343_

**Comment by hyf0** [comment]
@Boshen Fixing this requires more lifetime specifiers on `Parser` if you think this is acceptable if could make a contribution for this.

**Comment by Boshen** [comment]
Does https://github.com/web-infra-dev/oxc/pull/712 work for you? Adding another lifetime will complicate things, I think we should "align" the lifetimes before passing them to the parser.

**Comment by hyf0** [comment]
I bring this up just for accuracy. I guess this is a trade-off for more accuracy or better DX.

I'm not blocked by this, so feel free to decide how to handle the issue.

**Comment by Boshen** [comment]
I don't think this is a issue.
