### ISSUE TITLE
perf(parser): improve trivia building

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/oxc#898]
Benchmark shows trivia building is costly https://github.com/web-infra-dev/oxc/pull/897

Adding things straight to a btreemap is not ideal. I think we can add the spans to a vec first, then build the btreemap when the data is actually requested by using a once cell.

**Comment by MichaReiser** [comment]
Have you considered using `binary_search` on the vec directly to avoid building a `BTreeMap` entirely?

**Comment by Boshen** [comment]
> Have you considered using `binary_search` on the vec directly to avoid building a `BTreeMap` entirely?

Oh nice another perf opportunity! I'll take a look at replacing `btreemap.range` with binary search later, I think what we have learned so far is that arrays are the best data structure, everything else are too slow :-)
